version: '3'

services:
  highperf_notebook:
    container_name: highperf_notebook
    user: root
    privileged: true
    image: psyoblade/data-engineer-notebook:1.4
    restart: always
    volumes:
      - ./spark/notebooks:/home/jovyan/work
    environment:
      - GRANT_SUDO=yes
    ports:
      - "14040:4040"
      - "14041:4041"
      - "18080:8080"
      - "18888:8888"
networks:
  default:
    name: highperf_network
